version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-*'
          - 'core-js'
          - 'cssnano'
          - 'cssnano-*'
          - 'css-loader'
          - 'mini-css-extract-plugin'
          - 'postcss'
          - 'postcss-*'
          - 'source-map-loader'
          - 'terser-*'
          - 'webpack'
          - 'webpack-*'

      test:
        patterns:
          - '@wdio/*'
          - 'chai'
          - 'devtools'
          - 'karma'
          - 'karma-*'
          - 'mocha'
          - 'puppeteer'
          - 'standard'
          - 'webdriverio'

      tools:
        patterns:
          - 'chalk'
          - 'cross-env'
          - 'dotenv'
          - 'husky'
          - 'npm-run-all'

    reviewers:
      - alphagov/design-system-developers

    schedule:
      interval: monthly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      - dependency-type: direct
      - dependency-name: caniuse-lite

    ignore:
      - dependency-name: "glob"
        dependency-type: "indirect"

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      interval: monthly
      time: '10:30'
      timezone: 'Europe/London'
